[package]
name = "asf_model_bav_prototype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lazy_static = "1.4"
rand_distr = "0.4.3"

