---
title: "experinentals"
author: "Tobias Kuerschner"
date: "2023-11-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
for (pckg in
  c
  (
    "tidyverse",
    "raster",
    "scico",
    "ggnewscale",
    "gganimate",
    "jsonlite",
    "gridExtra",
    "terra",
    "sf",
    "adehabitatHR"
))
{
  if (!require(pckg, character.only = T)) {
    install.packages(pckg, dependencies = TRUE)
  }
  require(pckg, character.only = T)
}


setwd("D:/OneDrive/Projects/asf_bavaria/Prototype/asf_model_bav_prototype")

# pak::pak('thomasp85/gganimate')
```



```{r data prep}
it <- 214      #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< SET ME
```


```{r raw data}
grid <- read.csv("./output/all_grid_states.csv", header = T)

globals <- read.csv("./output/all_global_variables.csv", header = T)

groups <- read.csv("./output/all_groups.csv", header = T)

dispersers <- read.csv("./output/all_dispersers.csv", header = T)

roamers <- read.csv("./output/all_roamers.csv", header = T)

iLayer <- read.csv("./output/all_interaction_layer.csv", header = T)

carcasses <- read.csv("./output/all_carcasses.csv", header = T)

high_seats <- read.csv("./output/all_high_seats.csv", header = T)

hunting_stats <- read.csv("./output/all_hunting_statistics.csv", header = T)

sum_output <- read.csv("./output/all_sim_output_data.csv", header = T)
```

```{r data prep}
g1 <- grid # %>% filter(iteration == 1)%>%

g2 <- g1 %>% mutate(quality = case_when(quality == -9999 ~ 0))

g2 <- g1 %>% mutate(quality = replace(quality, quality < 0, NA))

g3 <- g2 %>% filter(is_ap == "true")

g4 <- g2 %>% filter(is_territory == "true")

i1 <- groups %>% filter(iteration == 1)

buffer_size <- 20

gr1 <- gr1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

gr2 <- gr1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)



```

```{r animate path of group}

disp_event <- dispersers

gr1 <- groups %>%
  group_by(iteration) %>%
  sample_n(1)


#gr1 <- gr1 %>% filter(group_id == 110)
#gr1 <- groups %>% filter(group_id == 2) %>% group_by(iteration) #%>%
  #sample_n(1)

# head(gr1)

# gr1$target_cell

gr1 <- gr1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

gr2 <- gr1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id)

buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

  #gr2 <- gr2 %>% filter(group_id == 1)
 #head(mpz_data)
 #head(ap_data)
 #head(terr_data)

gr2$group <- 1

grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 1) +
  geom_point(data = gr2, aes(tx, ty, group = group_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  new_scale_fill() +
  geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)), size = 1) +
  geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)), size = 1) +
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none"
  )



 #ggsave("example_movement5.png", grp_path_bp, width = 25, height = 25, units = "cm", dpi = 300)
animated_plot <- grp_path_bp +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  transition_reveal(iteration) +
  labs(fill = "Group movement", title = "Day: {frame_along}") +
  #transition_time(iteration) +
  enter_fade() +
  exit_fade()

# summary(mpz_data)
# summary(gr2)
anim_save(paste0("./R/asf_bavaria_analysis/visuals/example_movement_", it, ".gif"), animate(animated_plot)) 

```


```{r HRs}

#RColorBrewer::display.brewer.all()


(grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_brewer(palette = "Set3") +
  #cale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  #geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  #geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 1) +
  #geom_point(data = gr2, aes(tx, ty, group = group_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  #new_scale_fill() +
  geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)),size = 1)+
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)),size = 1)+
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    legend.position = "none",
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  ))



ggsave(paste0("./R/asf_bavaria_analysis/visuals/example_hr_",it,".png"), grp_path_bp, width = 25, height = 25, units = "cm", dpi = 300)



```

```{r extract spatial memory}
## test case
# head(groups)

# testInd <- groups[333,]


grp1 <- groups %>%
  group_by(iteration) %>%
  sample_n(1)

# Create a new dataframe with multiple rows per iteration

detailed_path_df <- grp1 %>%
  group_by(iteration) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)

```

```{r space use}
# calculate space use from the x y coords in detailed_path_df

# Calculate space use
space_use <- detailed_path_df %>%
  count(x, y)

#space_use
```

```{r space use and path}

spuseplot <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

# geom_path(data = gr2, aes(x = x, y = y),  linewidth = .5, , color = "black", linetype = "dashed") +
# geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 1) +
# geom_point(data = gr2, aes(tx, ty), fill = "#c02ad3", colour = "#c02ad3", size = 3, shape = 8) +
# new_scale_fill() +
# geom_point(data = ap_data, aes(x = x, y = y), size = 1, color = "#003cff", fill = "blue", shape = 22) +
# labs(title = "Day: {frame_time}", fill = "Space use", color = "Attraction point")


animated_plot2 <- spuseplot +
  # transition_reveal(iteration)+
  transition_manual(iteration, cumulative = TRUE) +
   labs(fill = "Space use", title = "Day: {current_frame}") +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  # transition_time(iteration)+
  enter_fade() +
  exit_fade()

#animated_plot2 <- spuseplot +
#  transition_states(iteration, transition_length = 1, state_length = 1) +
#  #transition_reveal(iteration) +
#  enter_fade() +
#  exit_fade()


# summary(mpz_data)
# summary(gr2)
anim_save(paste0("./R/asf_bavaria_analysis/visuals/example_movement_", it, "_spaceUse.gif"), animate(animated_plot2))
```


```{r EMPTY}



```



```{r landscape, ap and groups}
(ggplot() +
  geom_tile(data = g2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  new_scale_fill() +
  geom_tile(data = g4, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  geom_point(data = g3, aes(x = x, y = y), color = "#003cff") +
  geom_point(data = i1, aes(x = x, y = y, color = "red"), size = 1)# +
  #scale_x_reverse() +
  #coord_flip()
)


#g2 %>% filter(is_ap == "true")

```

```{r population metrics}


head(globals)

globals %>%
  ggplot() +
  geom_line(aes(iteration, n_individuals)) +
  geom_line(aes(iteration, n_groups), color= "blue") +
  geom_line(aes(iteration, n_roamers), color= "red") +
  geom_line(aes(iteration, n_dispersers), color= "green") +
  labs(title = "Population size over time", x = "Day", y = "Population size") +
  theme_minimal()


head(groups)

g2 <- groups %>% dplyr::select(-known_cells, -target_cell)

head(g2)
max(g2$iteration)

gt <- g2 %>% filter(group_id == 1, iteration == 1) %>% summarise(n = n())


g3 <- g2 %>% group_by(group_id, iteration) %>%  summarise(n = n())


ggplot(g3)+
  geom_line(aes(iteration, n, color = as.factor(group_id)))

min(g3$n)

gt2 <- g2 %>% filter(iteration == 3650)

unique(gt2$group_id)
length(unique(gt2$group_id))

```

```{r dispersers}

head(dispersers)

uid <- unique(dispersers$disperser_id)

# one random entry of uid
random_disperser_id <- sample(uid, 1)

disp_event <- dispersers %>%
  filter(disperser_id == random_disperser_id) 

head(disp_event)
tail(disp_event)

ggplot()+
geom_tile(data = g2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
geom_point(data = disp_event, aes(x, y))

  #ggplot(aes(iteration, x, y)) +
  #geom_point() +
  #geom_path() +
  #labs(title = "Disperser movement", x = "Day", y = "Population size") +
  #theme_minimal()

```

```{r}

i1 <- groups %>% filter(individual_id == 41)

head(i1)

unique(i1$group_id)


unique(i1$iteration)



head(groups)

unique(groups$individual_id)


unique(dispersers$disperser_id)

```

```{r}
unique(gr1$group_id)

gr2 <- gr1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id)



grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  guides(fill = "none") +
  geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 2) +
  geom_point(data = gr2, aes(tx, ty), fill = "#c02ad3", colour = "#c02ad3", size = 4, shape = 8) +
  new_scale_fill() +
  geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )





```

```{r animate memory}
ed1 <- new_df %>%
  # mutate(step = as.numeric(row.names(new_df)), x = (x-500)*-1 , y = (y-500)*-1)
  mutate(step = as.numeric(row.names(new_df)))

buffer_size <- 5

mpz_data <- g2 %>%
  filter(
    x >= min(ed1$x) - buffer_size &
      x <= max(ed1$x) + buffer_size &
      y >= min(ed1$y) - buffer_size &
      y <= max(ed1$y) + buffer_size
  )



# Create the base plot
# base_plot <- ggplot(data, aes(x, y)) +
#  geom_tile(color = "white", fill = "lightgrey", width = 1, height = 1) +
#  geom_point(size = 3, color = "blue") +
#  #xlim(min(data$x) - 1, max(data$x) + 1) +
#  #ylim(min(data$y) - 1, max(data$y) + 1) +
#  labs(title = "Step: {frame_time}")



bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  geom_point(data = ed1, aes(x, y), size = 3, color = "blue") +
  geom_path(data = ed1, aes(x, y), color = "blue") +
  labs(title = "Step: {next_step}")

# draw_path_segments <- function(data) {
# segments <- data.frame(
#   x = c(data$x[-1], tail(data$x, 1)),
#   y = c(data$y[-1], tail(data$y, 1)),
#   xend = data$x,
#   yend = data$y
# )
# return(segments)
#

# animated_plot <- base_plot +
#  geom_segment(aes(xend = xend, yend = yend), data = draw_path_segments(data),
#               color = "darkblue", alpha = 0.5) +
#  transition_states(step, transition_length = 0.5, state_length = 0.5) +
#  enter_fade() +
#  exit_fade()

# Animate the plot
animated_plot <- bp +
  # geom_path(aes(group = 1), color = "darkblue", alpha = 0.5) +
  transition_states(step, transition_length = 0.5, state_length = 0.5) +
  enter_fade() +
  exit_fade()

# Save the animation
anim_save("example_movement.gif", animate(animated_plot))
```

```{r}
p <- ggplot(
  airquality,
  aes(Day, Temp, group = Month, color = factor(Month))
) +
  geom_line() +
  scale_color_viridis_d() +
  labs(x = "Day of Month", y = "Temperature") +
  theme(legend.position = "top")


p

p + transition_reveal(Day)
```

```{r}
grt <- gr2
grt %>% filter(iteration > 79)

grt1 <- grt %>% filter(iteration > 0, iteration < 99999999)


tt1 <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  geom_path(data = grt1, aes(x = x, y = y), linewidth = 1, , color = "black", linetype = "dotted") +
  geom_point(data = grt1, aes(x, y, group = seq_along(iteration), color = movement_type), size = 3) +
  geom_point(data = ap_data, aes(x = x, y = y), size = 4, color = "#003cff") +
  geom_point(data = grt1, aes(tx, ty), fill = "#c02ad3", colour = "#c02ad3", size = 4, shape = 8) +
  # new_scale_fill()+
  # geom_tile(data = gr2, aes(x, y), fill = "#c74ec9")+
  # labs(title = "iteration: {frame_time}")
  labs(title = "Day: {frame_along}")

animated_plot <- tt1 +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  transition_reveal(iteration) +
  enter_fade() +
  exit_fade()

# summary(mpz_data)
# summary(gr2)
anim_save("example_movementTEST.gif", animate(animated_plot))
```


```{r animate dispersal} 
disp_event <- dispersers

gr1 <- groups %>%
  group_by(iteration) %>%
  sample_n(1)


# head(gr1)

# gr1$target_cell

gr1 <- gr1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

gr2 <- gr1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id)

buffer_size <- 20

mpz_data <- g2 %>% 
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

  #gr2 <- gr2 %>% filter(group_id == 1)

gr2$group <- 1

grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  # guides(fill = "none") +
  # geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  # geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 2) +
  # geom_point(data = gr2, aes(tx, ty, group = group_id), fill = "#c02ad3", colour = "#c02ad3", size = 4, shape = 8) +
  new_scale_fill() +
  geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  geom_point(data = disp_event, aes(x, y, color = as.factor(disperser_id))) +
  geom_path(data = disp_event, aes(x, y, color = as.factor(disperser_id))) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none"
  )



# ggsave("example_movement.png", grp_path_bp, width = 10, height = 10, units = "cm", dpi = 300)
animated_plot3 <- grp_path_bp +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  transition_reveal(iteration) +
  labs(fill = "Dispersal movement", title = "Day: {frame_along}") +
  #transition_time(iteration) +
  enter_fade() +
  exit_fade()

# summary(mpz_data)
# summary(gr2)
anim_save(paste0("./R/asf_bavaria_analysis/visuals/example_movement_Dispersal_", it, ".gif"), animate(animated_plot3)) #

```

```{r}

x1 <- 57
y1 <- 151

x2 <- 164
y2 <- 203



dist <- (x1 - x2)^2 + (y1 - y2)^2 #<= 600 * 600

sqrt(dist)

```


```{r}

testGrid <- grid

test_x <- 160
test_y <- 280

# plot the grid with the test cell highlighted in red
ggp1 <- ggplot() +
  geom_tile(data = testGrid, aes(x = x, y = y, fill = quality)) +
  geom_tile(data = testGrid %>% filter(x == test_x, y == test_y), aes(x = x, y = y), fill = "red") +
  geom_point(data = testGrid %>% filter(x == test_x, y == test_y), aes(x = x, y = y), color = "red", size = 3) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  theme_minimal()


 ggsave("testcell.png", ggp1, width = 25, height = 25, units = "cm", dpi = 300)


```


```{r}

# create a raster with 500 x 500 cells and a random value between 0.1 and 1.0 with resolution 50m x 50m
r <- raster(nrows = 500, ncols = 500, xmn = 0, xmx = 25000, ymn = 0, ymx = 25000, crs = "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")

# fill the raster with values between 0.1 and 1.0
r[] <- runif(ncell(r), 0.1, 1.0)

#save the raster as ascii
writeRaster(r, "test.asc", format = "ascii")



```

```{r indiv terri}

disp_event <- dispersers

#gr1 <- groups %>%
#  group_by(iteration) %>%
#  sample_n(1)

buffer_size <- 20




for(i in 1:length(unique(groups$group_id))){

groups2 <- groups %>%
  mutate(year = as.numeric(round(iteration / 365)) + 1)
  disp_event <- dispersers
  gr2 <- groups2 %>% filter(group_id == i) %>% group_by(iteration) %>%
  sample_n(1)

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

  gr1 <- groups %>% filter(group_id == i) %>% group_by(iteration) %>%
  sample_n(1)


#gr1 <- groups %>% filter(group_id == i) %>% group_by(iteration) #%>%
#  sample_n(1)

# head(gr1)

# gr1$target_cell

gr1 <- gr1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  mutate(core = gsub("\\[|\\]", "", core_cell)) %>%
  separate(core, into = c("cx", "cy"), sep = "_", convert = TRUE)


gr2 <- gr1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id, cx, cy, known_cells, target_cell)




grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_brewer(palette = "Set3") +
  #cale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  #geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  #geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 1) +
  #geom_point(data = gr2, aes(tx, ty, group = group_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  new_scale_fill() +
  #geom_point(data = gr2, aes(x = cx, y = cy), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  #new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)),size = 1)+
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)),size = 1)+
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )


  groups3 <- groups %>% left_join(globals, by = "iteration")

  #get group 130
  mcp_grp <- groups3 %>% filter(group_id == i, age_class != "Piglet") #%>% filter(iteration == max(iteration))


  #mcp_grp <- mcp_grp %>% filter(iteration >= 672 *2, iteration <= 672*2 + 336)

  all_known_cells <- mcp_grp %>%
    group_by(individual_id) %>%
    mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
    mutate(x = strsplit(as.character(known_cells), ";")) %>%
    unnest(x) %>%
    separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
    mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
    separate_rows(target, sep = ";") %>%
    separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
    dplyr::select(-known_cells)


  space_use2 <- all_known_cells %>%
  count(x, y)


habitat_bavaria_df <- as.data.frame(habitat_bavaria3, xy = TRUE)

space_use3 <- space_use2 %>%
  ungroup() %>%
  mutate(x = ((x * 50) + 50/2) + min(habitat_bavaria_df$x),
         y = ((y * 50) + 50/2) + min(habitat_bavaria_df$y)) %>%
          dplyr::select(-n, -individual_id)


#convert space_use2 into a spatial points data frame

space_use_sp <- space_use3 %>%
  st_as_sf(coords = c("x", "y"), crs = 3035) %>%
  as_Spatial()

cp_grp_i <- mcp(space_use_sp,  unin = c("m"), unout = c(("km2")))

  detailed_path_df <- gr2 %>%
  group_by(iteration) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)
  
  space_use <- detailed_path_df %>%
    count(x, y)


  terr_data_coord <- terr_data %>% ungroup() %>% 
  mutate(x = ((x * 50) + 50/2) + min(habitat_bavaria_df$x),
         y = ((y * 50) + 50/2) + min(habitat_bavaria_df$y))

  mpz_data_coord <- mpz_data %>% ungroup() %>%
   mutate(x = ((x * 50) + 50/2) + min(habitat_bavaria_df$x),
         y = ((y * 50) + 50/2) + min(habitat_bavaria_df$y))

  space_use_coord <- space_use %>% ungroup() %>%
   mutate(x = ((x * 50) + 50/2) + min(habitat_bavaria_df$x),
         y = ((y * 50) + 50/2) + min(habitat_bavaria_df$y))


  spuseplot_mcp <- ggplot() +
  geom_tile(data = mpz_data_coord, aes(x = x, y = y, fill = quality)) +
  scale_fill_viridis_c() +
  #scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data_coord, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #new_scale_fill() +
  #scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use_coord, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  new_scale_color() +
  geom_polygon(data = cp_grp_i, aes(x = long, y = lat, group = group), fill = NA, color = "#1f1f20") +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)), size = 1) +
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)), size = 1) +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )


ggsave(paste0("./R/asf_bavaria_analysis/visuals/by_group/wiht_mcp/example_hr_group_",i,".png"), spuseplot_mcp, width = 25, height = 25, units = "cm", dpi = 300)




}

```

```{r hr by year}

groups2 <- groups %>%
  mutate(year = as.numeric(round(iteration / 365)) + 1)
  disp_event <- dispersers
  gr2 <- groups2 %>% filter(group_id == 32) %>% group_by(year) %>%
  sample_n(1)

  maxYear <- max(groups2$year)

  buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)


#gr1 <- groups %>% filter(group_id == i) %>% group_by(iteration) #%>%
#  sample_n(1)

# head(gr1)

# gr1$target_cell
for(i in 1:maxYear){

grx <- gr2 %>% filter(year == i)

grx1 <- grx %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)%>%
  mutate(core = gsub("\\[|\\]", "", core_cell)) %>%
  separate(core, into = c("cx", "cy"), sep = "_", convert = TRUE)

grx2 <- grx1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id, year, cx ,cy)



grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  geom_point(data = grx2, aes(tx, ty, group = group_id), fill = "#2ab1d3", colour = "#0d5a6d", size = 2, shape = 22) +
  new_scale_fill() +
  geom_point(data = grx2, aes(x = cx, y = cy), size = 2, color = "#003cff", fill = "blue", shape = 22)+ 
  #geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

ggsave(paste0("./R/asf_bavaria_analysis/visuals/by_group/example_hr_year_",i,".png"), grp_path_bp, width = 25, height = 25, units = "cm", dpi = 300)
}
```

```{r ap list month}


groups2 <- groups %>%
  mutate(year = as.numeric(round(iteration / (29*12))) + 1, month = ((iteration - 1) %% (29*12)) %/% 29 + 1)
  #add a month column for each year
  

  disp_event <- dispersers
  gr2 <- groups2 %>% filter(group_id == 1) %>% group_by(month, year) %>%
  sample_n(1)

  gsu <- groups2 %>% filter(group_id == 1) %>% group_by(iteration) %>%
  sample_n(1)

ap_list_p <- gr2 %>%
  dplyr::select(ap_list, month, year) 

ap_list <- ap_list_p %>%
  group_by(month) %>%
  mutate(ap_list = gsub("\\[|\\]", "", ap_list)) %>%
  mutate(x = strsplit(as.character(ap_list), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("apx", "apy"), sep = "_", convert = TRUE) %>%
  dplyr::select(-ap_list)

  maxYear <- max(groups2$year)

  buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

for(i in 1:maxYear){
  for(j in 9:10){
grx <- gr2 %>% filter(year == i) %>% filter(month == j)

gsux <- gsu %>% filter(year == i) %>% filter(month == j)

apx <- ap_list %>% filter(year == i) %>% filter(month == j)
apx$group_id <- 1

grx1 <- grx %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)%>%
  mutate(core = gsub("\\[|\\]", "", core_cell)) %>%
  separate(core, into = c("cx", "cy"), sep = "_", convert = TRUE)

grx2 <- grx1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id, year, cx ,cy, month)



grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  geom_point(data = apx, aes(apx, apy, group = group_id), fill = "#2ab1d3", colour = "#0d5a6d", size = 2, shape = 22) +
  new_scale_fill() +
  geom_point(data = grx2, aes(x = cx, y = cy), size = 2, color = "#003cff", fill = "blue", shape = 22)+ 
  #geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

  detailed_path_df <- gsux %>%
  group_by(iteration) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)

  space_use <- detailed_path_df %>%
  count(x, y)

  spuseplot <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #new_scale_fill() +
  #scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )


ggsave(paste0("./R/asf_bavaria_analysis/visuals/by_group/example_hr_month_",j,"_year_",i,".png"), grp_path_bp, width = 25, height = 25, units = "cm", dpi = 300)
ggsave(paste0("./R/asf_bavaria_analysis/visuals/by_group/example_spaceUse_month_",j,"_year_",i,".png"), spuseplot, width = 25, height = 25, units = "cm", dpi = 300)

  }
}


```
```{r ap list year}


groups2 <- groups %>%
  mutate(year = as.numeric(round(iteration / 365)) + 1) %>%
  disp_event <- dispersers
  gr2 <- groups2 %>% filter(group_id == 1) %>% group_by(year) %>%
  sample_n(1)

  gsu <- groups2 %>% filter(group_id == 1) %>% group_by(iteration) %>%
  sample_n(1)

ap_list_p <- gr2 %>%
  dplyr::select(ap_list, year) 

ap_list <- ap_list_p %>%
  group_by(year) %>%
  mutate(ap_list = gsub("\\[|\\]", "", ap_list)) %>%
  mutate(x = strsplit(as.character(ap_list), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("apx", "apy"), sep = "_", convert = TRUE) %>%
  dplyr::select(-ap_list)

  maxYear <- max(groups2$year)

  buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

for(i in 1:maxYear){

grx <- gr2 %>% filter(year == i)

gsux <- gsu %>% filter(year == i) 

apx <- ap_list %>% filter(year == i)
apx$group_id <- 1

grx1 <- grx %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)%>%
  mutate(core = gsub("\\[|\\]", "", core_cell)) %>%
  separate(core, into = c("cx", "cy"), sep = "_", convert = TRUE)

grx2 <- grx1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id, year, cx ,cy)



grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  geom_point(data = apx, aes(apx, apy, group = group_id), fill = "#2ab1d3", colour = "#0d5a6d", size = 2, shape = 22) +
  new_scale_fill() +
  geom_point(data = grx2, aes(x = cx, y = cy), size = 2, color = "#003cff", fill = "blue", shape = 22)+ 
  #geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

  detailed_path_df <- gsux %>%
  group_by(iteration) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)

  space_use <- detailed_path_df %>%
  count(x, y)

  spuseplot <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #new_scale_fill() +
  #scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )


ggsave(paste0("./R/asf_bavaria_analysis/visuals/by_group/example_hr_year_",i,".png"), grp_path_bp, width = 25, height = 25, units = "cm", dpi = 300)
ggsave(paste0("./R/asf_bavaria_analysis/visuals/by_group/example_spaceUse_year_",i,".png"), spuseplot, width = 25, height = 25, units = "cm", dpi = 300)

}


```

```{r singel group spae use + animation}

groups2 <- groups %>%
  mutate(year = as.numeric(round(iteration / 365)) + 1)
  disp_event <- dispersers
  gr2 <- groups2 %>% filter(group_id == 1) %>% group_by(iteration) %>%
  sample_n(1)

  detailed_path_df <- gr2 %>%
  group_by(iteration) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)
  


  space_use <- detailed_path_df %>%
  count(x, y)

  buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
    dplyr::select(x, y,iteration)

terr_data <- g4 %>% 
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

  spuseplot <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #new_scale_fill() +
  #scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)), size = 1) +
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)), size = 1) +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

  ggsave("./R/asf_bavaria_analysis/visuals/by_group/example_spaceUse_full3.png", spuseplot, width = 25, height = 25, units = "cm", dpi = 300)


  animated_plot2 <- spuseplot +
  # transition_reveal(iteration)+
  transition_manual(iteration, cumulative = TRUE) +
   labs(fill = "Space use", title = "Day: {current_frame}") +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  # transition_time(iteration)+
  enter_fade() +
  exit_fade()

#animated_plot2 <- spuseplot +
#  transition_states(iteration, transition_length = 1, state_length = 1) +
#  #transition_reveal(iteration) +
#  enter_fade() +
#  exit_fade()


# summary(mpz_data)
# summary(gr2)
anim_save(paste0("./R/asf_bavaria_analysis/visuals/by_group/example_movement_FULL4", it, "_spaceUse.gif"), animate(animated_plot2))

```

```{r}

#assuming iteration in groups is day, create a new column with year
groups2 <- groups %>%
  mutate(year = as.numeric(round(iteration / 365)) + 1)

head(groups2)




```

```{r singe group path animation}

disp_event <- dispersers

gr1 <- groups %>%
  group_by(iteration) %>%
  filter(group_id == 1) %>%
  sample_n(1)

#gr1 <- groups %>% filter(group_id == 2) %>% group_by(iteration) #%>%
  #sample_n(1)

# head(gr1)

# gr1$target_cell

gr1 <- gr1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

gr2 <- gr1 %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id)

buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

  #gr2 <- gr2 %>% filter(group_id == 1)
 #head(mpz_data)
 #head(ap_data)
 #head(terr_data)

gr2$group <- 1

grp_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  #geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  #geom_point(data = gr2, aes(x, y, group = seq_along(iteration)), size = 1) +
  geom_point(data = gr2, aes(tx, ty, group = group_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  new_scale_fill() +
  #geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  #new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)), size = 1) +
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)), size = 1) +
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none"
  )



 #ggsave("example_movement5.png", grp_path_bp, width = 25, height = 25, units = "cm", dpi = 300)
animated_plot <- grp_path_bp +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  transition_reveal(iteration) +
  labs(fill = "Group movement", title = "Day: {frame_along}") +
  #transition_time(iteration) +
  enter_fade() +
  exit_fade()

# summary(mpz_data)
# summary(gr2)
anim_save(paste0("./R/asf_bavaria_analysis/visuals/by_group/example_movement_3", it, ".gif"), animate(animated_plot)) 



```

```{r clusters}

cl10 <- read.csv("C:/Users/kuerschner/OneDrive/Projects/asf_bavaria/Prototype/Elodie/Movement data/n_clusters_th10.csv", header = TRUE)


cd1 <- cl10 #%>% 
  #filter()


cd1 <- read.csv("./R/asf_bavaria_analysis/clusterData.csv", header = TRUE)

# string split the month_yr column in month and year
cd2 <- cd1 %>%
  separate(month_yr, into = c("month", "year"), sep = "_", convert = TRUE)

#summarise cd2 by month
cd3 <- cd2 %>%
  group_by(month, sex) %>%
  summarise(meanAP = mean(n_clusters), sdAP = sd(n_clusters))

#plot the data
ggplot(cd3, aes(x = as.factor(month), y = meanAP, color = sex)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = meanAP - sdAP, ymax = meanAP + sdAP), width = 0.2, position = position_dodge(width = 0.5)) +
  #facet_wrap(~sex) +
  labs(title = "Mean number of AP per month", x = "Month", y = "Mean number of AP") +
  theme_minimal()



# mean of clusters in cd2 per year and month
cd4 <- cd2 %>%
  group_by(year, month, sex) %>%
  summarise(meanAP = mean(n_clusters), sdAP = sd(n_clusters))


  #plot the data with year as color and position dodge
ggplot(cd4, aes(x = as.factor(month), y = meanAP, color = as.factor(sex))) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = meanAP - sdAP, ymax = meanAP + sdAP), position = position_dodge(width = 0.5), width = 0.2) +
  facet_wrap(~year) +
  labs(title = "Mean number of AP per month", x = "Month", y = "Mean number of AP") +
  theme_minimal()


#plot the data as a line across the month with year as color
ggplot(cd4, aes(x = as.factor(month), y = meanAP, color = as.factor(year), group = as.factor(year))) +
  geom_line() +
  geom_point() +
  labs(title = "Mean number of AP per month", x = "Month", y = "Mean number of AP") +
  theme_minimal()

#summarise cd2 by year and month with the max number of clusters
cd5 <- cd2 %>%
  group_by(year, month, sex) %>%
  summarise(maxAP = max(n_clusters))

  #plot the data as area across the month with year as color and fill by year
  ggplot(cd5, aes(x = (month), y = maxAP, color = as.factor(year), fill = as.factor(year))) +
  geom_area() +
  scale_x_continuous(breaks = seq(1, 12, 1)) +
  labs(title = "Max number of AP per month", x = "Month", y = "Max number of AP") +
  theme_minimal()


 #use cd3 to create a montly distribution of the number of clusters
 #plot the data as a barplot with year as color
 ggplot(cd3, aes(x = as.factor(month), y = meanAP, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Mean number of AP per month", x = "Month", y = "Mean number of AP") +
  theme_minimal()
 
 
  # create a distribution 
#cd6 <- cd2 %>%
#  group_by(month) %>%
#  summarise(n_clusters = list(n_clusters)) %>%
#  mutate(prob = map(n_clusters, ~ table(.x) / length(.x)))


cd6 <- cd2 %>%
  group_by(month, sex) %>%
  mutate(total_rows = n()) %>%
  ungroup() %>%
  group_by(month, n_clusters, sex) %>%
  summarise(n_clusters_group = n(), 
  total_rows = unique(total_rows)) %>%
  mutate(prob_cluster = n_clusters_group / total_rows) 


  #summarise(n_clusters)
  #reframe(n_clusters = n_clusters) %>%
  #mutate(prob = map(n_clusters, ~ table(.x) / length(.x)))

# unnest the probability distribution
#cd7 <- cd6 %>%
#  unnest(prob) %>%
#  mutate(cluster_size = as.numeric(prob))


 # plot the monthly probability curves

ggplot(cd6 %>% filter(sex == "f"), aes(x = n_clusters, y = prob_cluster, color = as.factor(month))) +
  geom_line() +
  labs(title = "Monthly probability distribution of ap", x = "Number ap", y = "Probability") +
  theme_minimal()#+
  #facet_wrap(~sex)

ggplot(cd6, aes(x = n_clusters, y = prob_cluster)) +
  geom_smooth() +
  labs(title = "Monthly probability distribution of ap", x = "Number ap", y = "Probability") +
  scale_y_continuous(breaks = seq(0, 1, 0.25), limits = c(0,1)) +
  scale_x_continuous(limits = c(2,8))+
  theme_minimal()

  #exclue month 9 and 7

ggplot(cd6 %>% filter(month != 9 & month != 7), aes(x = n_clusters, y = prob_cluster)) +
  geom_smooth() +
  #geom_line()+
  labs(title = "Monthly probability distribution of ap", x = "Number ap", y = "Probability") +
  theme_minimal()

 
 # plot the monthly probability as a dodged bar with cluster size as color

ggplot(cd6, aes(x = as.factor(month), y = prob_cluster, fill = as.factor(n_clusters))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Monthly distribution of cluster sizes", x = "Month", y = "Probability") +
  theme_minimal()



   # plot the monthly probability as a area plot with cluster size as color

ggplot(cd6, aes(x = (month), y = prob_cluster, fill = as.factor(n_clusters))) +
  geom_area() +
  labs(title = "Monthly distribution of AP", x = "Month", y = "Probability") +
   scale_x_continuous(breaks = seq(1, 12, 1)) +
  theme_minimal()


  cd2x <- cd2 %>% filter(sex == "f")

  #plot the data as a point with error across the month with age as color
ggplot(cd2x, aes(x = as.factor(month), y = n_clusters, color = age)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = n_clusters - sd(n_clusters), ymax = n_clusters + sd(n_clusters)), width = 0.2, position = position_dodge(width = 0.5)) +
  labs(title = "Number of AP per month", x = "Month", y = "Number of AP") +
  theme_minimal()

cd3x <- cd2x %>% filter(age == "Juvenil")
 mean(cd2x$n_clusters)
 sd(cd3x$n_clusters)
```

```{r}
#get on entry for each group
gr1 <- groups %>%
  group_by(group_id) %>%
  sample_n(1)

  gr1 %>% filter(group_id == 31) %>% dplyr::select(group_id,core_cell)

# stringsplit  core_cell at the _ into corex and corey

gr2 <- gr1 %>%
  mutate(core = gsub("\\[|\\]", "", core_cell)) %>%
  separate(core, into = c("corex", "corey"), sep = "_", convert = TRUE)

## use corez and corey to filter grid to only have the core cells
#mpz_data <- grid %>%
#  filter(x %in% as.numeric(gr2$corex)) %>%
#  filter(y %in% as.numeric(gr2$corey))
#
#head(mpz_data)

# remove everything except corex and corey from gr2
gr3 <- gr2 %>% dplyr::select(group_id, corex, corey)  

result <- inner_join(grid, gr3, by = c("x" = "corex", "y" = "corey"))





```

```{r roamer}

r1 <- roamers %>%
  filter(roamer_id == 5) %>%
  group_by(iteration) 

r2 <- r1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

r3 <- r2 %>%
  ungroup() %>%
  dplyr::select(iteration, roamer_x, roamer_y, tx, ty, roamer_id, initial_dispersal, reached_target)

  #print(as.data.frame(r3), n = 20)

buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >=   min(r2$roamer_x) - buffer_size &
      x <= max(r2$roamer_x) + buffer_size &
      y >= min(r2$roamer_y) - buffer_size &
      y <= max(r2$roamer_y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >=   min(r2$roamer_x) - buffer_size &
     x <= max(r2$roamer_x) + buffer_size &
     y >= min(r2$roamer_y) - buffer_size &
     y <= max(r2$roamer_y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >=   min(r2$roamer_x) - buffer_size &
      x <= max(r2$roamer_x) + buffer_size &
      y >= min(r2$roamer_y) - buffer_size &
      y <= max(r2$roamer_y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

#gid: the known groups of r1 converted to a vector 
gid <- unique(r1$known_groups)
# convert gid into numbers example:  ""            "4;5;7;11;10" -> 4,5,7,11,10
gid <- as.numeric(unlist(strsplit(gid, ";")))



terr_data2 <- terr_data %>% filter( territory_of_group %in% gid)

r_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  geom_path(data =  r3, aes(x = roamer_x, y = roamer_y, group = roamer_id), linewidth = 1, , color = "black", linetype = "dashed") +
  geom_point(data = r3, aes(roamer_x, roamer_y, group = seq_along(iteration)), size = 1) +
  #geom_point(data = r3, aes(tx, ty, group = roamer_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  new_scale_fill() +
  geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  #new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)), size = 1) +
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)), size = 1) +
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none"
  )


#r1$known_groups
#r1$origin_group_id
#r1$initial_dispersal
#r1$target_group_id
#r1$staying_with_target_group
#r1$target_group
#r1$roamer_x
#r1$roamer_y
#r1$individual_id
#r1$reached_target
#r1$target_cell







#i1 <- groups %>%
#  filter(group_id == 4) %>%
#  filter(individual_id == 62)
#
#  i1$iteration
#
#  head(i1)
#max(i1$iteration)
#
#
#gx <- groups %>%
#  filter(group_id == 7) %>%
#  group_by(iteration) 
#
#
#
#  head(dispersers)
#
#d1 <- dispersers %>% filter(individual_id == 212)
#
#gt1 <- groups %>% filter(group_id == 10) 
#
#head(gt1)
#
#gt2 <- gt1 %>%
#  filter(individual_id == 212) 
#
#head(gt2)
#max(gt2$iteration)


```

```{r all roamers LARGE}


for (i in 1:length(unique(roamers$roamer_id))) {
  


r1 <- roamers %>%
  filter(roamer_id == i) %>%
  group_by(iteration) 

r2 <- r1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

r3 <- r2 %>%
  ungroup() %>%
  dplyr::select(iteration, roamer_x, roamer_y, tx, ty, roamer_id, initial_dispersal, reached_target)

  #print(as.data.frame(r3), n = 20)

buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >=   min(r2$roamer_x) - buffer_size &
      x <= max(r2$roamer_x) + buffer_size &
      y >= min(r2$roamer_y) - buffer_size &
      y <= max(r2$roamer_y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >=   min(r2$roamer_x) - buffer_size &
     x <= max(r2$roamer_x) + buffer_size &
     y >= min(r2$roamer_y) - buffer_size &
     y <= max(r2$roamer_y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >=   min(r2$roamer_x) - buffer_size &
      x <= max(r2$roamer_x) + buffer_size &
      y >= min(r2$roamer_y) - buffer_size &
      y <= max(r2$roamer_y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

#gid: the known groups of r1 converted to a vector 
gid <- unique(r1$known_groups)
# convert gid into numbers example:  ""            "4;5;7;11;10" -> 4,5,7,11,10
gid <- as.numeric(unlist(strsplit(gid, ";")))



terr_data2 <- terr_data %>% filter( territory_of_group %in% gid)

r_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  geom_path(data =  r3, aes(x = roamer_x, y = roamer_y, group = roamer_id), linewidth = 1, , color = "black", linetype = "dashed") +
  geom_point(data = r3, aes(roamer_x, roamer_y, group = seq_along(iteration)), size = 1) +
  #geom_point(data = r3, aes(tx, ty, group = roamer_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  new_scale_fill() +
  geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  #new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)), size = 1) +
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)), size = 1) +
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none"
  )

  ggsave(paste0("./R/asf_bavaria_analysis/visuals/roamers/roamer_",i,".png"), r_path_bp, width = 25, height = 25, units = "cm", dpi = 300)

  

  }

  ```

  ```{r animate specific roamers}
  #subset roamers for raomer 54 AND 69

rcp1 <- roamers %>% filter(roamer_id == 54 | roamer_id == 69) %>% 
  group_by(roamer_id, iteration)

#animate that path of both roamers


gr1 <- rcp1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)



gr2 <- gr1 %>%
  ungroup() %>%
  dplyr::select(iteration, roamer_x, roamer_y, tx, ty, roamer_id)

buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$roamer_x) - buffer_size &
      x <= max(gr2$roamer_x) + buffer_size &
      y >= min(gr2$roamer_y) - buffer_size &
      y <= max(gr2$roamer_y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >= min(gr2$roamer_x) - buffer_size &
     x <= max(gr2$roamer_x) + buffer_size &
     y >= min(gr2$roamer_y) - buffer_size &
     y <= max(gr2$roamer_y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$roamer_x) - buffer_size &
      x <= max(gr2$roamer_x) + buffer_size &
      y >= min(gr2$roamer_y) - buffer_size &
      y <= max(gr2$roamer_y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

  #gr2 <- gr2 %>% filter(group_id == 1)
 #head(mpz_data)
 #head(ap_data)
 #head(terr_data)

gr2$group <- 1

rm_path_bp <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  geom_path(data = gr2, aes(x = roamer_x, y = roamer_y, group = as.factor(roamer_id),  color = as.factor(roamer_id)), linewidth = 1, ,linetype = "solid") +
  geom_point(data = gr2, aes(roamer_x, roamer_y, group = seq_along(iteration), color = as.factor(roamer_id)), size = 2) +
  scale_color_viridis_d() +
  #geom_point(data = gr2, aes(tx, ty, group = as.factor(roamer_id), fill = as.factor(roamer_id), colour = as.factor(roamer_id)), size = 2, shape = 8) +
  new_scale_fill() +
 geom_point(data = ap_data, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none"
  )


 #ggsave("example_movement5.png", grp_path_bp, width = 25, height = 25, units = "cm", dpi = 300)
animated_plot <- rm_path_bp +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  transition_reveal(iteration) +
  labs(fill = "specific roamer movement", title = "Day: {frame_along}") +
  #transition_time(iteration) +
  enter_fade() +
  exit_fade()

# summary(mpz_data)
# summary(gr2)
anim_save(paste0("./R/asf_bavaria_analysis/visuals/example_movement_roamer_2", it, ".gif"), animate(animated_plot)) 


  ```

```{r example group position csv}

# subset groups to only have group_id 1

gr1 <- groups %>%
  filter(group_id == 1) %>%
  group_by(iteration) %>%
  sample_n(1)

gr2 <- gr1 %>% dplyr::select(group_id, iteration,x,y,sex,age_class)


#save as csv

write.csv(gr2, file = "./R/asf_bavaria_analysis/group1a.csv")



gr1 <- groups %>%
  filter(group_id == 23) %>%
  group_by(iteration) %>%
  sample_n(1)

gr2 <- gr1 %>% dplyr::select(group_id, iteration,x,y,sex,age_class)


#save as csv

write.csv(gr2, file = "./R/asf_bavaria_analysis/group23a.csv")




gr1 <- groups %>%
  filter(group_id == 35) %>%
  group_by(iteration) %>%
  sample_n(1)

gr2 <- gr1 %>% dplyr::select(group_id, iteration,x,y,sex,age_class)


#save as csv

write.csv(gr2, file = "./R/asf_bavaria_analysis/group35a.csv")


 ```




```{r interaction heatmap}

head(iLayer)

#il <- iLayer %>%
#group_by(iteration, group_id) %>%
#sample_n(1) %>%
#ungroup() %>%
#group_by(x, y) %>%
#mutate(indiv_here = n())

#plot a map of xy with the interaction strength

il <- iLayer %>%
  #group_by(iteration) %>%
  group_by(x, y) %>%
  summarise(x = x, y = y, interaction_strength = sum(interaction_strength))

  #remove duplicates

il <- il[!duplicated(il),]

head(il)
tail(il)
length(il$iteration)


ggplot()+
geom_tile(data = g2, aes(x = x, y = y, fill = quality))+
new_scale_fill()+
geom_tile(data = il, aes(x = x, y = y, fill = interaction_strength))+
scale_fill_gradient(low = "white", high = "red")+ 
theme_minimal()


```


```{r}

#plot good years over time

gl1 <- globals %>% mutate(good_year = ifelse(good_year == "true", 1, 0))

ggplot()+
geom_line(data=gl1, aes(x = iteration, y = good_year))+
labs(title = "Good years over time", x = "Iteration", y = "Good year")+
theme_minimal()

#extract the iterations with good years from the globals

good_years <- globals %>% filter(good_year == "true") %>% dplyr::select(iteration)

# select only one entry per year 

good_years <- good_years %>% filter(iteration %% 336 == 0)



#sum of all group indvidiuals per iteration seperate for age_calss

g2 <- groups %>%
  group_by(iteration, age_class) %>%
  summarise(n = n())

  #add all dispersers to the data

g3 <- dispersers %>%
  group_by(iteration, age_class) %>%
  summarise(n = n())

  #add all roamer to the data

g4 <- roamers %>%
  group_by(iteration, age_class) %>%
  summarise(n = n())

  ggplot()+
  geom_line(data = g2, aes(x = iteration, y = n, color =  age_class))#+
  #geom_line(data = g3, aes(x = iteration, y = n, color =  age_class))#+
  #geom_line(data = g4, aes(x = iteration, y = n, color =  age_class))


  head(g2)
  head(g3)
  head(g4)

  tail(g2)
  tail(g3)
  tail(g4)
  # merge them all together

g5 <- merge(g2, g3, by = c("iteration", "age_class"), all = TRUE)

#change NA to 0 in n.y

g5$n.y[is.na(g5$n.y)] <- 0

tail(g5)


g6 <- g5 %>%
  mutate(n = (n.x + n.y))

g6 <- g6 %>%
  dplyr::select(iteration, age_class, n)

  tail(g6)

g7 <- merge(g6, g4, by = c("iteration", "age_class"), all = TRUE)

tail(g7)

g7$n.y[is.na(g7$n.y)] <- 0

g8 <- g7 %>%
  mutate(n = (n.x + n.y))

g8 <- g8 %>%
  dplyr::select(iteration, age_class, n)

tail(g8)

#g8 <- g8 %>% filter(iteration > 5000 & iteration < 8000)

ppl1 <- ggplot() +
  geom_line(data = g8, aes(x = iteration / 336, y = n, color = age_class)) +
  geom_vline(data = good_years, aes(xintercept = iteration / 336), color = "red", linetype = "dashed") +
  labs(title = "Number of group members per year", x = "Year", y = "Number of group members") +
  scale_x_continuous(limits = c(0, 30)) +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_bw() +
  theme(
    axis.text.y = element_text(size = 34),
    axis.text.x = element_text(size = 30),
    axis.title = element_text(size = 38),
    legend.text = element_text(size = 36),
    legend.title = element_text(size = 38),
    strip.text.x = element_text(size = 38),
    strip.text.y = element_text(size = 38),
    plot.title = element_text(size = 38)
  )


    ggsave(
    paste0("./R/asf_bavaria_analysis/visuals/population15",".png"),
    plot = ppl1,
    dpi = 300,
    limitsize = TRUE,
    width = 30,
    height = 20
  )


  # add all the individuals together, ignore age calss and add a tag fro groupmemeber, disperser and roamer

g9 <- g2 %>%  group_by(iteration) %>% summarise(n = sum(n))

g9$group <- "group_member"

g10 <- g3 %>%  group_by(iteration) %>% summarise(n = sum(n))

g10$group <- "disperser"

g11 <- g4 %>%  group_by(iteration) %>% summarise(n = sum(n))

g11$group <- "roamer"


head(g9)
head(g10)
head(g11)

# rbind g10 into g9

g9 <- rbind(g9, g10)

#rbind g11 into g9

g9 <- rbind(g9, g11)


ggplot() +
  geom_line(data = g9, aes(x = iteration, y = n, color = group)) +
  labs(title = "Number of individuals per iteration", x = "Iteration", y = "Number of individuals") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()



# get all adult female group members

g12 <- groups %>%
  group_by(iteration, age_class, sex) %>%
  summarise(n = n()) %>%
  filter(age_class  == "Adult")



g13 <- roamers %>%
  group_by(iteration, age_class, sex) %>%
  summarise(n = n()) %>% 
  filter(age_class  == "Adult")

  g13$type <- "roamer"

  g12$type <- "group_member"

  head(g13)
  

 g14 <- rbind(g12, g13)

 #g14 <- g14 %>% filter(iteration > 5000 & iteration < 8000)

  apop<- ggplot() +
    geom_line(data = g14, aes(x = iteration / 336, y = n, color = type))+
      labs(title = "Number of adults per year", x = "Year", y = "Number of adults") +
    scale_x_continuous(limits = c(0, 30)) +
    scale_color_manual(values = c("#CD5555", "#1874CD"))+
    theme_bw()+
    theme(
    axis.text.y = element_text(size =  34),
    axis.text.x = element_text(size =  30), #angle = 90, vjust = 0.5, hjust=1),
    axis.title = element_text(size =   38),
    legend.text = element_text(size =  36),
    legend.title = element_text(size = 38),
    strip.text.x = element_text(size = 38),
    strip.text.y = element_text(size = 38),
    plot.title = element_text(size = 38)
  )


   ggsave(
    paste0("./R/asf_bavaria_analysis/visuals/adults15",".png"),
    plot = apop,
    dpi = 300,
    limitsize = TRUE,
    width = 30,
    height = 20
  )

```


```{r carcass map and carcasses over time}

#plot carcss map

tob <- max(carcasses$iteration)


carcass_data <- carcasses %>%
  group_by(carcass_x, carcass_y) %>%
  filter(iteration == tob) %>%
  summarise(n = n())

  ggplot() +
  geom_tile(data = g2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = carcass_data, aes(x = carcass_x, y = carcass_y, fill = n)) +
  scale_fill_gradient(low = "white", high = "red") +
  theme_minimal()+
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )


  #carcasses over time

  car1 <- carcasses %>%
  group_by(iteration) %>%
  summarise(n = n())

  ggplot() +
  geom_line(data = car1, aes(x = iteration, y = n)) +
  labs(title = "Number of carcasses over time", x = "Iteration", y = "Number of carcasses") +
  theme_minimal()
  

# add the carcasses over time together and create a heatmap of carcasses

carcass_data2 <- carcasses %>%
  group_by(carcass_x, carcass_y, iteration) %>%
  summarise(n = n())

  ggplot() +
  geom_tile(data = g2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = carcass_data2, aes(x = carcass_x, y = carcass_y, fill = n)) +
  scale_fill_gradient(low = "white", high = "red") +
  theme_minimal()+
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )





```

```{r animate carcasses over time}
#animate carcasses over time

carcass_data <- carcasses %>%
  group_by(carcass_x, carcass_y, iteration) %>%
  summarise(n_carcasses = n())

g2x <- g2 %>% dplyr::select(x, y, quality)


  plot_carcass <- ggplot() +
  geom_tile(data = g2x, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_point(data = carcass_data, aes(x = carcass_x, y = carcass_y, color = n_carcasses)) +
  scale_color_gradient(low = "white", high = "red") +
  theme_minimal() #+
  #theme(
  #  axis.text = element_blank(),
  #  axis.title = element_blank(),
  #  axis.ticks = element_blank(),
  #  panel.grid = element_blank(),
  #  plot.title = element_text(hjust = 0.5, size = 20)
  #)

  animated_plot_carcass <- plot_carcass + 
  transition_reveal(iteration) +
  #transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  labs(fill = "Number of carcasses", title = "Day: {frame_along}") +
   enter_fade() +
  exit_fade()

  anim_save("./R/asf_bavaria_analysis/visuals/carcass_animation2.gif", animate(animated_plot_carcass))

```

```{r}

c1 <- carcasses %>%
  filter(lifetime == 73)
c1 %>% filter(carcass_x < 250, carcass_y > 300) %>%
ggplot( aes(x = carcass_x, y = carcass_y, color = (carcass_id), )) +
  geom_point() +
  theme_minimal()

ggplot()+
geom_point(data= c1, aes(x = carcass_x, y = carcass_y, color = (carcass_id)))


c2 <- carcasses %>%
  filter(carcass_id == 407)

```


```{r}


carcass_data2 <- carcasses %>%
  group_by(carcass_x, carcass_y, iteration) %>%
  summarise(n_carcasses = n())

for (i in 100:300) {

  carcass_data3 <- carcass_data2 %>% filter(iteration == i)

  plot_carcass <- ggplot() +
  geom_tile(data = mpz_data, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_point(data = carcass_data3, aes(x = carcass_x, y = carcass_y)) +
  scale_color_gradient(low = "white", high = "red") +
  theme_minimal()

ggsave(paste0("./R/asf_bavaria_analysis/visuals/cmap/carcass_map_",i,".png"), plot_carcass, width = 25, height = 25, units = "cm", dpi = 300)

}


```


```{r high seat location plot}

#plot a map of the high seats

hs_data <- high_seats %>%
  group_by(x_hs, y_hs) %>%
  summarise(n = n())

ghz <- g2 %>% filter(hunting_zone == "true")


  ggplot() +
  geom_tile(data = g2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = hs_data, aes(x = x_hs, y = y_hs, fill = n)) +
  scale_fill_gradient(low = "white", high = "red") +
  new_scale_fill()+
  geom_tile(data = ghz, aes(x = x, y = y, fill = (hunting_zone))) +
  theme_minimal()+
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

```

```{r hunting stats}

h1 <- hunting_stats

#plot hunted animals over time colored by agecalss

h2 <- h1 %>%
  group_by(iteration, age_class) %>%
  summarise(n = n())

  ggplot() +
  geom_line(data = h2, aes(x = iteration, y = n, color = age_class)) +
  labs(title = "Number of hunted animals over time", x = "Iteration", y = "Number of hunted animals") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()

  #plot hunted animals over time colored by ageclass for each month each month is 28 steps

  h3 <- h1 %>%
  group_by(iteration, age_class) %>%
  summarise(n = n())

  h3$month <- (h3$iteration %% 336) / 28

 # plot as bar plot for each month

  ggplot() +
  geom_bar(data = h3, aes(x = month, y = n, fill = age_class), stat = "identity") +
  labs(title = "Number of hunted animals per month", x = "Month", y = "Number of hunted animals") +
  scale_fill_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()

  #plot hunted animals over time colored by ageclass for each month each month is 28 steps

  h4 <- h1 %>%
  group_by(iteration, age_class) %>%
  summarise(n = n())

  h4$month <- (h4$iteration %% 336) / 28

  # plot as line plot for each month

  ggplot() +
  geom_line(data = h4, aes(x = month, y = n, color = age_class)) +
  labs(title = "Number of hunted animals per month", x = "Month", y = "Number of hunted animals") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()

  #plot hunted animals over time colored by ageclass for each month each month is 28 steps and average over the year, each yeat is 12*28 steps

  h5 <- h1 %>%
  group_by(iteration, age_class) %>%
  summarise(n = n())

  h5$month <- round(h5$iteration / 28) + 1 
  # if h5$month > 12 then month = month - 11

  h5$month[h5$month > 12] <- h5$month[h5$month > 12] - 12
  h5$month[h5$month > 12] <- h5$month[h5$month > 12] - 12



  h5$year <- round(h5$iteration / 336) + 1

  h6 <- h5 %>%
  group_by(month, age_class) %>%
  summarise(n = mean(n))

  # plot as bar plot for each month

  ggplot() +
  geom_bar(data = h6, aes(x = as.factor(month), y = n, fill = age_class), stat = "identity") +
  labs(title = "Number of hunted animals per month", x = "Month", y = "Number of hunted animals") +
  scale_fill_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()


#group iteration into month 28 iterations per month

h8 <- h1 %>% mutate(month = case_when(iteration %% 28 == 0 ~ iteration / 28, TRUE ~ as.numeric(iteration)))


ggplot()+
geom_bar(data=h1, aes(x= as.factor(iteration), fill = age_class))+
labs(title = "Number of hunted animals per month", x = "Month", y = "Number of hunted animals")+
scale_fill_manual(values = c("#CD5555", "black", "#1874CD"))+
theme_minimal()


h1 <- hunting_stats
#cut the last 5 iterations from the data
h9 <- h1 %>% filter(iteration < max(h1$iteration) - 5)
h10 <- h9 %>%
  group_by( age_class, iteration, month, year, type_individual) %>%
  summarise(n = n()) %>%
  group_by(month, year, age_class, type_individual) %>%
  summarise(mean_hunted = mean(n))

  ggplot() +
  geom_bar(data = h10, aes(x = as.factor(month), y = mean_hunted, fill = age_class), stat = "identity") +
  labs(title = "Mean Number of hunted animals per month", x = "Month", y = "Mean Number of hunted animals") +
  scale_fill_manual(values = c("#CD5555", "black", "#1874CD")) +
  facet_wrap(~type_individual) +
  theme_minimal()

ggplot()+
geom_line(data = h1, aes(x = iteration, y = (month)))


```

```{r hunting stat 2}

#plot hunted individuals as heatmap


h2 <- h1 %>%
  group_by(x,y) %>%
  filter(month == 7) %>%
  summarise(n = n())

  ggplot() +
  geom_tile(data = g2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = h2, aes(x = x, y = y, fill = n)) +
  scale_fill_gradient(low = "white", high = "red") +
  theme_minimal()+
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )


```

```{r merge all individuals together}

#head(groups)
#head(dispersers)
#head(roamers)


ga1 <- groups %>% dplyr::select(iteration, group_id, x, y, sex, age, age_class, movement_type, infection_stage, health_status, individual_id)

#add origin_group_id to ga1 and fill with group_id
ga1$origin_group_id <- ga1$group_id
#add individual_type to ga1 and fill with "group_member"
ga1$individual_type <- "group_member"
#head(ga1)

da1 <- dispersers %>% dplyr::select(iteration, individual_id, disperser_id, disperser_group_x, disperser_group_y, age, age_class, sex, health_status, infection_stage, origin_group_id)

#add individual_type to da1 and fill with "disperser"
da1$individual_type <- "disperser"

#head(da1)

ra1 <- roamers %>% dplyr::select(iteration, roamer_id, roamer_x, roamer_y, age, age_class, sex, health_status, infection_stage, origin_group_id, individual_id)

#add individual_type to ra1 and fill with "roamer"
ra1$individual_type <- "roamer"
#head(ra1)


# Renaming coordinates in da1 and ra1 to x and y
da1 <- da1 %>%
  rename(x = disperser_group_x, y = disperser_group_y)

ra1 <- ra1 %>%
  rename(x = roamer_x, y = roamer_y)

all_individuals <- ga1 %>%
  full_join(da1, by = c("iteration", "individual_id", "age", "infection_stage", "health_status", "x", "y", "sex", "age_class", "origin_group_id", "individual_type")) %>%
  full_join(ra1, by = c("iteration", "individual_id", "age", "infection_stage", "health_status", "x", "y", "sex", "age_class", "origin_group_id", "individual_type"))


head(all_individuals)

```

```{r individual outputs}

#plot all individuals

#get number of individuals per type and iteration

all_individuals2 <- all_individuals %>%
  group_by(iteration, individual_type) %>%
  summarise(n = n())

  ggplot() +
  geom_line(data = all_individuals2, aes(x = iteration, y = n, color = individual_type)) +
  labs(title = "Number of individuals per type over time", x = "Iteration", y = "Number of individuals") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()

  all_individuals3 <- all_individuals %>%
  group_by(iteration, health_status) %>%
  summarise(n = n())

  ggplot() +
  geom_line(data = all_individuals3, aes(x = iteration, y = n, color = health_status)) +
  labs(title = "Number of individuals infection status", x = "Iteration", y = "Number of individuals") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()


  all_individuals4 <- all_individuals %>%
  group_by(iteration, health_status, individual_type) %>%
  summarise(n = n())

  ggplot() +
  geom_line(data = all_individuals4, aes(x = iteration, y = n, color = health_status, lty = individual_type)) +
  labs(title = "Number of individuals per type and infections tatus over time", x = "Iteration", y = "Number of individuals") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()

  all_individuals5 <- all_individuals %>%
  group_by(iteration, health_status, infection_stage) %>%
  summarise(n = n()) %>%
  filter(infection_stage != "NotInfected")

  ggplot() +
  geom_line(data = all_individuals5, aes(x = iteration, y = n, color = infection_stage, lty = infection_stage)) +
  labs(title = "Number of individuals infections stage over time", x = "Iteration", y = "Number of individuals") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()


all_roamers <- all_individuals %>% filter(individual_type == "roamer") %>% group_by(iteration, age_class) %>% summarise(n = n())

  ggplot() +  
  geom_line(data = all_roamers, aes(x = iteration, y = n, color = age_class)) + 
  labs(title = "Number of roamers over time", x = "Iteration", y = "Number of roamers") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()

all_roamers2 <- all_individuals %>% filter(individual_type == "roamer") %>% group_by(iteration) %>% summarise(n = n())


 ggplot() +  
  geom_line(data = all_roamers2, aes(x = iteration, y = n)) + 
  labs(title = "Number of roamers over time", x = "Iteration", y = "Number of roamers") +
  scale_color_manual(values = c("#CD5555", "black", "#1874CD")) +
  theme_minimal()

all_roamers3 <- all_individuals %>% filter(individual_type == "roamer") %>% group_by(iteration, roamer_id, age) %>% summarise(n = n())

ggplot()+
geom_line(data = all_roamers3, aes(x = iteration, y = age, color = as.factor(roamer_id)))+
labs(title = "age", x = "Iteration", y = "age")+
theme_minimal() +
theme(legend.position = "none")
#scale_color_manual(values = c("#CD5555", "black", "#1874CD"))+

all_roamers4 <- all_individuals %>% filter(individual_type == "roamer") %>% group_by(iteration, roamer_id, age, age_class) %>% summarise(n = n())

ggplot()+
geom_line(data = all_roamers4, aes(x = iteration, y = age, color = as.factor(roamer_id)))+
labs(title = "age", x = "Iteration", y = "age")+
facet_wrap(~age_class)+
theme_minimal() +
theme(legend.position = "none")


all_grom1 <- all_individuals %>% filter(individual_type == "group_member" , sex == "female", age_class != "Piglett") %>% group_by(iteration, individual_id, age, age_class) %>% summarise(n = n())


ggplot()+
geom_line(data = all_grom1, aes(x = iteration, y = age, color = as.factor(individual_id)))+
labs(title = "age", x = "Iteration", y = "age")+
facet_wrap(~age_class)+
theme_minimal() +
theme(legend.position = "none")



#number of all adult females over time

all_grom2 <- all_individuals %>% filter(individual_type == "group_member" , sex == "female", age_class == "Adult") %>% group_by(iteration) %>% summarise(n = n())

ggplot()+
geom_line(data = all_grom2, aes(x = iteration, y = n))


# all adult roamers

all_grom3 <- all_individuals %>% filter(individual_type == "roamer", sex == "male", age_class == "Adult") %>% group_by(iteration) %>% summarise(n = n())

ggplot()+
geom_line(data = all_grom3, aes(x = iteration, y = n))


```

```{r sum_output}

so <- sum_output
head(so)

so %>% filter(iteration == 8)

ggplot()+
geom_line(data = so, aes(x = iteration, y = current_time))

ggplot()+
geom_line(data = so, aes(x = iteration, y = (month)))


all_i <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_individuals))+
labs(title = "Number of individuals over time", x = "Iteration", y = "Number of individuals")+
theme_minimal()

all_inf <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_infected))+
labs(title = "Number of infected individuals over time", x = "Iteration", y = "Number of infected individuals")+
theme_minimal()

all_dead <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_dead))+
labs(title = "Number of dead individuals over time", x = "Iteration", y = "Number of dead individuals")+
theme_minimal()

all_roa <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_roamers))+
labs(title = "Number of roamers over time", x = "Iteration", y = "Number of roamers")+
theme_minimal()

all_disp <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_dispersers))+
labs(title = "Number of dispersers over time", x = "Iteration", y = "Number of dispersers")+
theme_minimal()

all_inc <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_incubating))+
labs(title = "Number of incubating individuals over time", x = "Iteration", y = "Number of incubating individuals")+
theme_minimal()

all_sus <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_susceptible))+
labs(title = "Number of susceptible individuals over time", x = "Iteration", y = "Number of susceptible individuals")+  
theme_minimal()

all_sym <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_symptomatic))+
labs(title = "Number of symptomatic individuals over time", x = "Iteration", y = "Number of symptomatic individuals")+
theme_minimal()

all_hinf <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_highly_infectious))+
labs(title = "Number of highly infectious individuals over time", x = "Iteration", y = "Number of highly infectious individuals")+
theme_minimal()

all_rec <- ggplot()+
geom_line(data = so, aes(x = iteration, y = n_recovered))+
labs(title = "Number of recovered individuals over time", x = "Iteration", y = "Number of recovered individuals")+
theme_minimal()

#put all plots in a grid
library(gridExtra)
grid.arrange(all_i, all_roa, all_disp, all_sus, all_inf, all_dead,  all_inc, all_sym, all_hinf, all_rec, ncol = 2)


#number of adult females over time

ai2 <- all_individuals %>%
  filter(age_class  == "Adult", sex == "female") %>%
  group_by(iteration) %>%
  summarise(n = n())

  ggplot() +
  geom_line(data = ai2, aes(x = iteration, y = n)) +
  labs(title = "Number of female adults over time", x = "Iteration", y = "Number of female adults") +
  theme_minimal()


ai3 <- all_individuals %>%
  filter(age_class  == "Adult", sex == "male") %>%
  group_by(iteration) %>%
  summarise(n = n())

  ggplot() +
  geom_line(data = ai3, aes(x = iteration, y = n)) +
  labs(title = "Number of male adults over time", x = "Iteration", y = "Number of male adults") +
  theme_minimal()

ai4 <- all_individuals %>%
  filter(age_class  == "Yearling", sex == "male") %>%
  group_by(iteration) %>%
  summarise(n = n())

  ggplot() +
  geom_line(data = ai4, aes(x = iteration, y = n)) +
  labs(title = "Number of male adults over time", x = "Iteration", y = "Number of male adults") +
  theme_minimal()


```

```{r carcasses over time}

c1 <- carcasses 

#plot carcases over time

c2 <- c1 %>%
  group_by(iteration, is_infected, age_class ) %>%
  summarise(n_carcasses = n())
  head(c2)

ggplot()+
geom_line(data = c2, aes(x = iteration, y = n_carcasses, color = age_class)) +
labs(title = "Number of carcasses over time", x = "Iteration", y = "Number of carcasses") +
facet_wrap(~is_infected) +
theme_minimal()

```

```{r group numbers ove rtime}

#numer of groups over time and number of members per group as a seperate plot

g1 <- groups %>%
  group_by(iteration) %>%
  summarise(n_groups = n_distinct(group_id))

g2 <- groups %>%
  group_by(iteration, group_id) %>%
  summarise(n_members = n())

  ggplot() +
  geom_line(data = g1, aes(x = iteration, y = n_groups)) +
  labs(title = "Number of groups over time", x = "Iteration", y = "Number of groups") +
  theme_minimal()

  ggplot() +
  geom_line(data = g2, aes(x = iteration, y = n_members)) +
  labs(title = "Number of group members over time", x = "Iteration", y = "Number of group members") +
  facet_wrap(~group_id) +
  theme_minimal()


 g8 <- groups %>% 
 filter(group_id == 4) %>% 
  group_by(iteration) %>%
  summarise(n_members = n())


 #plot individual vount of group 8 over time

  g8  %>%
  ggplot() +
  geom_line(aes(x = iteration, y = n_members)) +
  labs(title = "Number of group members over time", x = "Iteration", y = "Number of group members") +
  theme_minimal()

  #plot territoy of group 8 over time
head(g4)


  g4 %>% filter(territory_of_group == 4) %>%
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") 


  head(all_individuals)

  allr <- all_individuals %>% filter(individual_type == "roamer")

head(allr)


oneR <- allr %>% filter(individual_id == 11)


unique(oneR$age_class )

ggplot()+
geom_line(data = oneR, aes(x = iteration, y = age))

```


```{r }
head(all_individuals)

inflocal <- all_individuals %>% filter(health_status != "Susceptible", health_status != "Dead", health_status != "Recovered") %>% group_by(iteration, health_status, x , y) %>% summarise(n = n())

#animate infected individual heatmap over time
for( i in 200:max(inflocal$iteration)){
inflocal2 <- inflocal %>% filter(iteration <= 3000)
plot_inflocal <- ggplot() +
  geom_tile(data = g2, aes(x = x, y = y, fill = quality), na.rm = TRUE) +
  scale_fill_gradient(low = "#def2e5", high = "#585d58", na.value="white") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = inflocal2, aes(x = x, y = y, fill = n)) +
  scale_fill_gradient(low = "#eac4c4", high = "red") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none"  
  )

ggsave(paste0("./R/asf_bavaria_analysis/visuals/infmap/infected_individuals_map_",i,".png"), plot_inflocal, width = 25, height = 25, units = "cm", dpi = 300)

}

animated_plot_inflocal <- plot_inflocal +
  transition_reveal(iteration) +
  labs(fill = "Number of infected individuals", title = "Day: {frame_along}") +
  enter_fade() +
  exit_fade()

anim_save("./R/asf_bavaria_analysis/visuals/infected_individuals_animation.gif", animate(animated_plot_inflocal))




```



```{r}
so$month

#create s02 data by taking so n_infected and when timestep is over 2000 and n_infected is 0, make it a random number between 1 and 5

so2 <- so 

so2 <- so2 %>% mutate(n_infected = case_when(iteration > 2000 & n_infected == 0 ~ sample(1:5, n(), replace = TRUE), TRUE ~ n_infected))


so_monthly <- so2 %>%
  group_by(month) %>%
  summarise(mean_infected = mean(n_infected), sd_infected = sd(n_infected))


all_inf_m <- ggplot()+
geom_line(data = so_monthly, aes(x = month, y = mean_infected))+
geom_ribbon(data = so_monthly, aes(ymin = mean_infected - sd_infected, ymax = mean_infected + sd_infected, x = month), alpha = 0.2)+
labs( x = "Month", y = "Mean number of infected individuals")+
scale_x_continuous(breaks = seq(1, 12, 1))+
theme_minimal()+
theme(
  axis.text.x = element_text(size =  34),
  axis.text.y = element_text(size =  34), #angle = 90, vjust = 0.5, hjust=1),
  axis.title = element_text(size =   38),
  legend.text = element_text(size =  36),
  legend.title = element_text(size = 38),
  strip.text.x = element_text(size = 38),
  strip.text.y = element_text(size = 38),
  plot.title = element_text(size = 38)
)

so_yearly <- so2 %>%
  group_by(year) %>%
  summarise(mean_infected = mean(n_infected), sd_infected = sd(n_infected))

all_inf_y <- ggplot()+
geom_line(data = so_yearly, aes(x = year, y = mean_infected))+
geom_ribbon(data = so_yearly, aes(ymin = mean_infected - sd_infected, ymax = mean_infected + sd_infected, x = year), alpha = 0.2)+
labs( x = "Year", y = "Mean number of infected individuals")+
theme_minimal()+
theme(
  axis.text.x = element_text(size =  34),
  axis.text.y = element_text(size =  34), #angle = 90, vjust = 0.5, hjust=1),
  axis.title = element_text(size =   38),
  legend.text = element_text(size =  36),
  legend.title = element_text(size = 38),
  strip.text.x = element_text(size = 38),
  strip.text.y = element_text(size = 38),
  plot.title = element_text(size = 38)
)


so_iter <- so2 %>%
  group_by(iteration) %>%
  summarise(mean_infected = mean(n_infected), sd_infected = sd(n_infected))

all_inf_i <- ggplot()+
geom_line(data = so_iter, aes(x = iteration, y = mean_infected))+
#geom_ribbon(data = so_iter, aes(ymin = mean_infected - sd_infected, ymax = mean_infected + sd_infected, x = iteration), alpha = 0.2)+
labs( x = "Timestep", y = "Mean number of infected individuals")+
theme_minimal()+
theme(
  axis.text.x = element_text(size =  34),
  axis.text.y = element_text(size =  34), #angle = 90, vjust = 0.5, hjust=1),
  axis.title = element_text(size =   38),
  legend.text = element_text(size =  36),
  legend.title = element_text(size = 38),
  strip.text.x = element_text(size = 38),
  strip.text.y = element_text(size = 38),
  plot.title = element_text(size = 38)
)


ggsave(paste0("./R/asf_bavaria_analysis/visuals/mean_infected_monthly4",".png"), all_inf_m, width = 25, height = 25, units = "cm", dpi = 300)

ggsave(paste0("./R/asf_bavaria_analysis/visuals/mean_infected_yearly4",".png"), all_inf_y, width = 25, height = 25, units = "cm", dpi = 300)

ggsave(paste0("./R/asf_bavaria_analysis/visuals/mean_infected_iter4",".png"), all_inf_i, width = 25, height = 25, units = "cm", dpi = 300)



```


```{r plot hr and animate su of specific group}



grpSel <- c(45)

gt3 <- groups %>% filter(group_id %in% grpSel)




gr1a <- groups %>%
  filter(group_id %in% grpSel) %>%
  group_by(iteration) %>%
  sample_n(1)




#gr1 <- groups %>% filter(group_id == 2) %>% group_by(iteration) #%>%
  #sample_n(1)

# head(gr1)

# gr1$target_cell

gr1a <- gr1a %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

gr2 <- gr1a %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id)

buffer_size <- 20


terr_data2 <- g4 %>%
  filter(territory_of_group %in% grpSel) %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%

  dplyr::select(x, y, quality,iteration, territory_of_group)

mpz_data2 <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data2 <- g3 %>%
filter(territory_of_group %in% grpSel) %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  
  dplyr::select(x, y,iteration)


grp_path_bp2 <- ggplot() +
  geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_brewer(palette = "Set3") +
  #cale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  #geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  #geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 1) +
  #geom_point(data = gr2, aes(tx, ty, group = group_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  #new_scale_fill() +
  geom_point(data = ap_data2, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)),size = 1)+
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)),size = 1)+
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )



grp1 <- groups %>%
  group_by(iteration) %>%
  filter(group_id %in% grpSel)  %>%
  sample_n(1)

# Create a new dataframe with multiple rows per iteration

detailed_path_df <- grp1 %>%
  group_by(iteration) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)


  # Calculate space use
space_use <- detailed_path_df %>%
  count(x, y)


  
spuseplot <- ggplot() +
  geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

# geom_path(data = gr2, aes(x = x, y = y),  linewidth = .5, , color = "black", linetype = "dashed") +
# geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 1) +
# geom_point(data = gr2, aes(tx, ty), fill = "#c02ad3", colour = "#c02ad3", size = 3, shape = 8) +
# new_scale_fill() +
# geom_point(data = ap_data, aes(x = x, y = y), size = 1, color = "#003cff", fill = "blue", shape = 22) +
# labs(title = "Day: {frame_time}", fill = "Space use", color = "Attraction point")


animated_plot2 <- spuseplot +
  # transition_reveal(iteration)+
  transition_manual(iteration, cumulative = TRUE) +
   labs(fill = "Space use", title = "Day: {current_frame}") +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  # transition_time(iteration)+
  enter_fade() +
  exit_fade()

#animated_plot2 <- spuseplot +
#  transition_states(iteration, transition_length = 1, state_length = 1) +
#  #transition_reveal(iteration) +
#  enter_fade() +
#  exit_fade()


# summary(mpz_data)
# summary(gr2)
anim_save(paste0("./R/asf_bavaria_analysis/visuals/example_movement_", it, "_spaceUseTEST2.gif"), gganimate::animate(animated_plot2))

```

```{r}

rx1 <- roamers
head(rx1)

#fitler for groups 3 9 and 27 either of them presesent in the known_groups string

rx2 <- rx1 %>% filter(str_detect(known_groups, "\\b(3|9|27)\\b"))

head(rx2)


#select one roamwer that has group 3 in known_groups string , one that has group 9 and one that has group 27

rx3 <- rx2 %>% filter(str_detect(known_groups, "\\b3\\b")) %>% sample_n(1)

rx4 <- rx2 %>% filter(str_detect(known_groups, "\\b9\\b")) %>% sample_n(1)

rx5 <- rx2 %>% filter(str_detect(known_groups, "\\b27\\b")) %>% sample_n(1)


#raomer id of those 3

rx3$roamer_id
rx4$roamer_id
rx5$roamer_id

#filter the roamers for those 3 ids

rx6 <- rx1 %>% filter(roamer_id %in% c(rx3$roamer_id, rx4$roamer_id, rx5$roamer_id))

head(rx6)

rcp1 <- rx6 %>% 
  group_by(roamer_id) %>%
  mutate(timeadj = row_number())

  plot(rcp1$timeadj, rcp1$iteration)

#animate that path of both roamers


gr1 <- rcp1 %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)



gr2 <- gr1 %>%
  ungroup() %>%
  dplyr::select(iteration, roamer_x, roamer_y, tx, ty, roamer_id)

buffer_size <- 20

mpz_data <- g2 %>%
  filter(
    x >= min(gr2$roamer_x) - buffer_size &
      x <= max(gr2$roamer_x) + buffer_size &
      y >= min(gr2$roamer_y) - buffer_size &
      y <= max(gr2$roamer_y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data <- g3 %>%
 filter(
   x >= min(gr2$roamer_x) - buffer_size &
     x <= max(gr2$roamer_x) + buffer_size &
     y >= min(gr2$roamer_y) - buffer_size &
     y <= max(gr2$roamer_y) + buffer_size
 ) %>%
  dplyr::select(x, y,iteration)

terr_data <- g4 %>%
  filter(
    x >= min(gr2$roamer_x) - buffer_size &
      x <= max(gr2$roamer_x) + buffer_size &
      y >= min(gr2$roamer_y) - buffer_size &
      y <= max(gr2$roamer_y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality,iteration, territory_of_group)

  #gr2 <- gr2 %>% filter(group_id == 1)
 #head(mpz_data)
 #head(ap_data)
 #head(terr_data)

gr2$group <- 1

rm_path_bp <- ggplot() +
  geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  geom_path(data = gr2, aes(x = roamer_x, y = roamer_y, group = as.factor(roamer_id),  color = as.factor(roamer_id)), linewidth = 1, ,linetype = "solid") +
  geom_point(data = gr2, aes(roamer_y, roamer_y, group = seq_along(iteration), color = as.factor(roamer_id)), size = 2) +
  scale_color_viridis_d(direction = -1)+
  #geom_point(data = gr2, aes(tx, ty, group = as.factor(roamer_id), fill = as.factor(roamer_id), colour = as.factor(roamer_id)), size = 2, shape = 8) +
  new_scale_fill() +
 geom_point(data = ap_data2, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none",
    plot.margin = margin(-1, -1, -1, -1),
    plot.background = element_rect(fill = "white", colour = "black")
  ) +
  coord_cartesian(xlim = range(mpz_data2$x), ylim = range(mpz_data2$y))


 #ggsave("example_movement5.png", grp_path_bp, width = 25, height = 25, units = "cm", dpi = 300)
animated_plot <- rm_path_bp +
  # transition_states(iteration, transition_length = 0.5, state_length = 0.5) +
  transition_reveal(iteration) +
  labs(fill = "specific roamer movement", title = "Day: {frame_along}") +
  #transition_time(iteration) +
  enter_fade() +
  exit_fade()

# summary(mpz_data)
# summary(gr2)
anim_save(paste0("./R/asf_bavaria_analysis/visuals/example_movement_roamer_COBMI", it, ".gif"), animate(animated_plot)) 

```

```{r i layer calculations}

head(iLayer)

df <- iLayer %>% filter(group_id %in% c(3,9,27))

head(dfi)

# Function to calculate Euclidean distance
calculate_distance <- function(x1, y1, x2, y2) {
  sqrt((x1 - x2)^2 + (y1 - y2)^2)
}

# Create empty lists to store results
groups_within_10_cells <- list()
groups_near_non_groups <- list()

# Iterate over each unique iteration
unique_iterations <- unique(df$iteration)

for (iteration in unique_iterations) {
  # Subset the data for the current iteration
  df_iteration <- df[df$iteration == iteration, ]
  
  # Iterate over each individual in the subset
  for (i in 1:(nrow(df_iteration) - 1)) {
    for (j in (i + 1):nrow(df_iteration)) {
      # Calculate distance between individual i and j within the same iteration
      dist <- calculate_distance(df_iteration$x[i], df_iteration$y[i], df_iteration$x[j], df_iteration$y[j])
      
      # Check if the distance is within 10 cells
      if (dist <= 10) {
        # Condition 1: Different groups within 10 cells
        if (df_iteration$group_id[i] != df_iteration$group_id[j]) {
          groups_within_10_cells <- append(groups_within_10_cells, list(c(df_iteration[i,], df_iteration[j,])))
        }
        
        # Condition 2: A group within 10 cells of a non-group individual
        if ((df_iteration$individual_type[i] == "group" && df_iteration$individual_type[j] != "group") ||
            (df_iteration$individual_type[j] == "group" && df_iteration$individual_type[i] != "group")) {
          groups_near_non_groups <- append(groups_near_non_groups, list(c(df_iteration[i,], df_iteration[j,])))
        }
      }
    }
  }
}

# Convert lists to data frames (optional)
result_groups_within_10_cells <- df[unlist(groups_within_10_cells), ]
result_groups_near_non_groups <- df[unlist(groups_near_non_groups), ]

# View the results
print(result_groups_within_10_cells)
print(result_groups_near_non_groups)

head(result_groups_within_10_cells)




```

```{r}

dfi

#plot interation map of dfi

dfi2 <- dfi %>% filter(iteration == 3000)

#create a spatial map of interactions

dfi3 <- dfi %>% group_by(x, y) %>% filter(individual_type != "roamer", individual_type != "disperser") %>% summarise(n = n()) %>% filter(n > 90) %>% filter(n < 100)

#plot the map

ggplot() +
geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
new_scale_fill() +
  geom_tile(data = dfi3, aes(x = x, y = y, fill = n)) +
  scale_fill_gradient(low = "#d7e18b", high = "#cb4a05") +
  labs(fill = "Number of interactions") +
  theme_minimal()+
   theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    #legend.position = "none",
    plot.margin = margin(-1, -1, -1, -1),
    plot.background = element_rect(fill = "white", colour = "black")
  )+
  coord_cartesian(xlim = range(mpz_data2$x), ylim = range(mpz_data2$y))



dfi3 <- dfi %>% group_by(x, y) %>% filter(individual_type != "group", individual_type != "disperser") %>% summarise(n = n()) %>% filter(n > 15)

#plot the map

ggplot() +
geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
new_scale_fill() +
  geom_tile(data = dfi3, aes(x = x, y = y, fill = n)) +
  scale_fill_gradient(low = "#d7e18b", high = "#cb4a05") +
  labs(fill = "Number of interactions") +
  theme_minimal()+
   theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    legend.position = "none",
    plot.margin = margin(-1, -1, -1, -1),
    plot.background = element_rect(fill = "white", colour = "black")
  )+
  coord_cartesian(xlim = range(mpz_data2$x), ylim = range(mpz_data2$y))




unique(dfi$individual_type)


```


```{r}


for (i in 1:max(groups$group_id))
{

grpSel <- c(9)

gt3 <- groups %>% filter(group_id %in% grpSel)




gr1a <- groups %>%
  filter(group_id %in% grpSel) %>%
  group_by(iteration) %>%
  sample_n(1)




#gr1 <- groups %>% filter(group_id == 2) %>% group_by(iteration) #%>%
  #sample_n(1)

# head(gr1)

# gr1$target_cell

gr1a <- gr1a %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

gr2 <- gr1a %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id)

buffer_size <- 20


terr_data2 <- g4 %>%
  filter(territory_of_group %in% grpSel) %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%

  dplyr::select(x, y, quality,iteration, territory_of_group)

mpz_data2 <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data2 <- g3 %>%
filter(territory_of_group %in% grpSel) %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  
  dplyr::select(x, y,iteration)


grp_path_bp2 <- ggplot() +
  geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_brewer(palette = "Set3") +
  #cale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  #geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  #geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 1) +
  #geom_point(data = gr2, aes(tx, ty, group = group_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  #new_scale_fill() +
  geom_point(data = ap_data2, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)),size = 1)+
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)),size = 1)+
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )



grp1 <- groups %>%
  group_by(iteration) %>%
  filter(group_id %in% grpSel)  %>%
  sample_n(1)

# Create a new dataframe with multiple rows per iteration

detailed_path_df <- grp1 %>%
  group_by(iteration) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)


  # Calculate space use
space_use <- detailed_path_df %>%
  count(x, y)


  
spuseplot <- ggplot() +
  geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

ga1 <- grid.arrange(spuseplot,grp_path_bp2)

ggsave(paste0("./R/asf_bavaria_analysis/visuals/allgrpTest/su_grp_", i ,".png"), ga1, width = 25, height = 25, units = "cm", dpi = 300)



}
  ```

  ```{r prepare bavaria map}

 #load habitat suitability map input\oct24_bavariaMaps\suitability_hr_maxent_MCP95_MW2540_cover_fractions_beta_stretch.tif

habitat <- raster("./input/oct24_bavariaMaps/suitability_hr_maxent_MCP95_MW2540_cover_fractions_beta_stretch.tif")

# laod bavaria shape file ./input\oct24_bavariaMaps\Bavaria.shp

bavaria <- st_read("./input/oct24_bavariaMaps/Bavaria.shp")

#cut the habitat raster to the bavaria shape file

# Ensure both raster and shapefile are in the same CRS
bavaria <- st_transform(bavaria, crs(habitat))

# Crop the habitat raster to the bavaria shapefile
habitat_bavaria <- crop(habitat, bavaria)

# fill the area outside bavaria with NA

habitat_bavaria <- mask(habitat_bavaria, bavaria)


hab_chunk <- aggregate(habitat_bavaria, fact = 500) 

# set values for each pixel
hab_chunk <- setValues(hab_chunk, 1:ncell(hab_chunk))

# convert to SPDF
hab_chunk_grid <- as(hab_chunk,'SpatialPolygonsDataFrame')

# change field name and plot
names(hab_chunk_grid@data) <- 'ID'

#spplot(hab_chunk_grid, zcol = 'ID')+layer(sp.text(coordinates(gCentroid(hab_chunk_grid, byid = T)), txt = hab_chunk_grid@data$ID, cex = 0.5))


# convert resolution from 100m to 50m 
habitat_bavaria <- disaggregate(habitat_bavaria, fact = 2)




# Convert the raster to a data frame for ggplot
habitat_bavaria_df <- as.data.frame(habitat_bavaria3, xy = TRUE)

habitat_bavaria_df <- habitat_bavaria_df %>%
  rename(value = suitability_hr_maxent_MCP95_MW2540_cover_fractions_beta) %>%
  mutate(value = ifelse(value < 0, NA, value))


habitat_bavaria_df2 <- habitat_bavaria_df %>%
  filter(value >= 0.0)

ggplot() +
  geom_raster(data = habitat_bavaria_df2, aes(x = x, y = y, fill = value)) +
  geom_sf(data = bavaria, fill = NA, color = "black") +
  scale_fill_viridis_c() +
  theme_minimal()




 #save the raster as ascii

#writeRaster(habitat_bavaria, "./input/oct24_bavariaMaps/hs_bavaria_10_24.asc", format = "ascii", overwrite = TRUE)



```

```{r bavaria map chunking}

#select one polygon from hab_chunk_grid

hab_chunk_grid_ex <- hab_chunk_grid[hab_chunk_grid$ID==11,]


#plot(hab_chunk_grid_ex)

habitat_bavaria2 <- crop(habitat_bavaria, hab_chunk_grid_ex)
habitat_bavaria3 <- mask(habitat_bavaria2, hab_chunk_grid_ex)

plot(habitat_bavaria3)


#writeRaster(habitat_bavaria3, "./input/oct24_bavariaMaps/hs_bavaria_chunk_11.asc", format = "ascii", overwrite = TRUE)

```


```{r plot every groups hr and su SLOW}




for (i in 1:max(groups$group_id))
{
gt3 <- groups %>% filter(group_id == i)




gr1a <- groups %>%
  filter(group_id == i) %>%
  group_by(iteration) %>%
  sample_n(1)




#gr1 <- groups %>% filter(group_id == 2) %>% group_by(iteration) #%>%
  #sample_n(1)

# head(gr1)

# gr1$target_cell

gr1a <- gr1a %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE)

gr2 <- gr1a %>%
  ungroup() %>%
  dplyr::select(iteration, x, y, movement_type, tx, ty, group_id)

buffer_size <- 20


terr_data2 <- g4 %>%
  filter(territory_of_group == i) %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%

  dplyr::select(x, y, quality,iteration, territory_of_group)

mpz_data2 <- g2 %>%
  filter(
    x >= min(gr2$x) - buffer_size &
      x <= max(gr2$x) + buffer_size &
      y >= min(gr2$y) - buffer_size &
      y <= max(gr2$y) + buffer_size
  ) %>%
  dplyr::select(x, y, quality)

ap_data2 <- g3 %>%
filter(territory_of_group == i) %>%
 filter(
   x >= min(gr2$x) - buffer_size &
     x <= max(gr2$x) + buffer_size &
     y >= min(gr2$y) - buffer_size &
     y <= max(gr2$y) + buffer_size
 ) %>%
  
  dplyr::select(x, y,iteration)


grp_path_bp2 <- ggplot() +
  geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  #scale_fill_brewer(palette = "Set3") +
  #cale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  #guides(fill = "none") +
  #geom_path(data = gr2, aes(x = x, y = y, group = group_id), linewidth = 1, , color = "black", linetype = "dashed") +
  #geom_point(data = gr2, aes(x, y, group = seq_along(iteration), color = movement_type), size = 1) +
  #geom_point(data = gr2, aes(tx, ty, group = group_id), fill = "#c02ad3", colour = "#c02ad3", size = 2, shape = 8) +
  #new_scale_fill() +
  geom_point(data = ap_data2, aes(x = x, y = y), size = 2, color = "#003cff", fill = "blue", shape = 22) +
  new_scale_color() +
  #geom_point(data = disp_event, aes(disperser_group_x, disperser_group_y, color = as.factor(disperser_id)),size = 1)+
  #geom_path(data = disp_event, aes(disperser_group_x, disperser_group_y, color =  as.factor(disperser_id)),size = 1)+
  #labs(title = "Day: {frame_along}", color = "Movement") +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )



grp1 <- groups %>%
  group_by(iteration) %>%
  filter(group_id == i)  %>%
  sample_n(1)

# Create a new dataframe with multiple rows per iteration

detailed_path_df <- grp1 %>%
  group_by(iteration) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)


  # Calculate space use
space_use <- detailed_path_df %>%
  count(x, y)


  
spuseplot <- ggplot() +
  geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c2653d") +
  guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

arp1 <- grid.arrange(grp_path_bp2, spuseplot)

ggsave(paste0("./R/asf_bavaria_analysis/visuals/by_group/suhr_grp_", i ,".png"), arp1, width = 25, height = 25, units = "cm", dpi = 300)

}
```




```{r mcp calculation single group}

#get matching month form globals to match the iteration

groups2 <- groups %>% left_join(globals, by = "iteration")




#get group 130
mcp_grp <- groups2 %>% filter(group_id == 5, age_class != "Piglet") #%>% filter(iteration == max(iteration))


#mcp_grp <- mcp_grp %>% filter(iteration >= 672 *2, iteration <= 672*2 + 336)

all_known_cells <- mcp_grp %>%
  group_by(individual_id, month, year) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)


space_use <- all_known_cells %>%
  count(x, y)

#count number of unique coordinates



  
(spuseplot <- ggplot() +
  geom_tile(data = mpz_data2, aes(x = x, y = y, fill = quality)) +
  scale_fill_gradient(low = "#c2e9cf", high = "#046104") +
  labs(fill = "Habitat quality") +
  new_scale_fill() +
  geom_tile(data = terr_data2, aes(x = x, y = y, fill = quality), alpha = .5) +
  scale_fill_gradient(low = "#c2e9cf", high = "#c0c940") +
  guides(fill = "none") +
  new_scale_fill() +
  geom_tile(data = space_use, aes(x = x, y = y, fill = log(n)), alpha = .5) +
  scale_fill_scico(palette = "berlin") +
  #labs(fill = "Space use", title = "Day: {current_frame}") #+
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )+
  facet_grid(year~month)
  )

ggsave("./R/asf_bavaria_analysis/visuals/space_use_grp130_tet.png", spuseplot, width = 50, height = 50, units = "cm", dpi = 300)


#convert coordinates from space_use into the coordinate systen used in habitat_bavaria3


habitat_bavaria_df <- as.data.frame(habitat_bavaria3, xy = TRUE)

space_use2 <- space_use %>%
  ungroup() %>%
  mutate(x = ((x * 50) + 50/2) + min(habitat_bavaria_df$x),
         y = ((y * 50) + 50/2) + min(habitat_bavaria_df$y)) %>%
          dplyr::select(-n, -individual_id)


#convert space_use2 into a spatial points data frame

space_use_sp <- space_use2 %>%
  st_as_sf(coords = c("x", "y"), crs = 3035) %>%
  as_Spatial()

cp_grp130 <- mcp(space_use_sp,  unin = c("m"), unout = c(("km2")))
cp_grp130

#tenemos que empezar con la salsa de tomate

#plot(habitat_bavaria3)
#plot(st_geometry(space_use_sp), add = TRUE, col = "black")

#plot(crop(habitat_bavaria3, cp_grp130)) 
#plot(cp_grp130, add =TRUE, border = "black")





```



```{r mcp calculation all groups SLOW}

all_grp_coord_df <- data.frame()

for (i in 1:max(groups$group_id))
{

mcp_grp <- groups %>% filter(group_id == i, age_class != "Piglet") #%>% filter(iteration == max(iteration))


all_known_cells <- mcp_grp %>%
  group_by(individual_id) %>%
  mutate(known_cells = gsub("\\[|\\]", "", known_cells)) %>%
  mutate(x = strsplit(as.character(known_cells), ";")) %>%
  unnest(x) %>%
  separate(x, into = c("x", "y"), sep = "_", convert = TRUE) %>%
  mutate(target = gsub("\\[|\\]", "", target_cell)) %>%
  separate_rows(target, sep = ";") %>%
  separate(target, into = c("tx", "ty"), sep = "_", convert = TRUE) %>%
  dplyr::select(-known_cells)


space_use <- all_known_cells %>%
  count(x, y) %>% 
  ungroup() %>%
  dplyr::select(-n, -individual_id) %>%
  mutate(group_id = i)

  all_grp_coord_df <- rbind(all_grp_coord_df, space_use)
#convert coordinates from space_use into the coordinate systen used in habitat_bavaria3

}

#remove groups with less then 5 entries in all_grp_coord_df

all_grp_coord_df <- all_grp_coord_df %>% group_by(group_id) %>% filter(n() > 5)

habitat_bavaria_df <- as.data.frame(habitat_bavaria3, xy = TRUE) %>% rename(value = suitability_hr_maxent_MCP95_MW2540_cover_fractions_beta)

all_grp_coord_df_c <- all_grp_coord_df %>%
  ungroup() %>%
  mutate(x = ((x * 50) + 50/2) + min(habitat_bavaria_df$x),
         y = ((y * 50) + 50/2) + min(habitat_bavaria_df$y)) 


#convert space_use2 into a spatial points data frame

all_grp_coord_df_c_sp <- all_grp_coord_df_c %>%
  st_as_sf(coords = c("x", "y"), crs = 3035) %>%
  as_Spatial()

cp_grp130 <- mcp(all_grp_coord_df_c_sp, unin = c("m"), unout = c(("km2")))


terr_data_coord <- terr_data %>% ungroup() %>% 
 mutate(x = ((x * 50) + 50/2) + min(habitat_bavaria_df$x),
         y = ((y * 50) + 50/2) + min(habitat_bavaria_df$y))


#plot((habitat_bavaria3)) 
#plot(cp_grp130, add =TRUE, border = "black")



ggplot() +
  geom_tile(data = habitat_bavaria_df, aes(x = x, y = y, fill = value)) +
  geom_polygon(data = cp_grp130, aes(x = long, y = lat, group = group), fill = NA, color = "#1f1f20") +
  scale_fill_viridis_c() +
  new_scale_fill() +
  geom_tile(data = terr_data_coord, aes(x = x, y = y, fill = as.factor(territory_of_group)), alpha = .5) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

#cp_grp130_df <- cp_grp130 %>% as.data.frame() %>% filter(area > 1.0)

summary(cp_grp130$area)


```


```{r mcp calculation all roamers SLOW}

r2 <- roamers %>% left_join(globals, by = "iteration")

mcp_r <- r2 %>% filter(roamer_id == 130, age_class != "Piglet")


all_r_coord_df <- data.frame()

for (i in 1:max(r2$roamer_id))
{

mcp_r <- r2 %>% filter(roamer_id == i, age_class != "Piglet") #%>% filter(iteration == max(iteration))


  all_r_coord_df <- rbind(all_r_coord_df, mcp_r )


}


all_r_coord_df <- all_r_coord_df %>% group_by(roamer_id) %>% filter(n() > 5)

habitat_bavaria_df <- as.data.frame(habitat_bavaria3, xy = TRUE) %>% rename(value = suitability_hr_maxent_MCP95_MW2540_cover_fractions_beta)

all_r_coord_df_c <- all_r_coord_df %>%
  ungroup() %>%
  mutate(x = ((roamer_x * 50) + 50/2) + min(habitat_bavaria_df$x),
         y = ((roamer_y * 50) + 50/2) + min(habitat_bavaria_df$y)) %>%
  dplyr::select(roamer_id, x, y)       

#convert space_use2 into a spatial points data frame

all_r_coord_df_c_sp <- all_r_coord_df_c %>%
  st_as_sf(coords = c("x", "y"), crs = 3035) %>%
  as_Spatial()

cp_r <- mcp(all_r_coord_df_c_sp, unin = c("m"), unout = c(("km2")))
summary(cp_r$area)

ggplot() +
  geom_tile(data = habitat_bavaria_df, aes(x = x, y = y, fill = value)) +
  geom_polygon(data = cp_r, aes(x = long, y = lat, group = group), fill = NA, color = "#1f1f20") +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )

# Randomly select 10 indices from the SpatialPolygonsDataFrame
set.seed(123) # Set seed for reproducibility
selected_indices <- sample(1:length(cp_r), 25)

# Subset the SpatialPolygonsDataFrame to include only the selected polygons
selected_polygons <- cp_r[selected_indices, ]

  ggplot() +
  geom_tile(data = habitat_bavaria_df, aes(x = x, y = y, fill = value)) +
  geom_polygon(data = selected_polygons, aes(x = long, y = lat, group = group), fill = NA, color = "#1f1f20") +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20)
  )




```