---
title: "rust_pipeline"
author: "Tobias Kürschner"
date: '2024-01-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r R code to send input to Rust and receive output from Rust}

#use shiny to create a base parameter config file
shiny::runApp("R/asf_bavaria_analysis/model_config_app.r")


#or set it manulally

library(jsonlite)

config <- list(
  max_age                           = 365 * 12, #u32
  max_known_cells                   = 60,       #usize
  runtime                           = 365 * 6,  #usize
  adult_survival_day                = 0.9647,   #f64
  piglet_survival_day               = 0.9438,   #f64
  min_stay_time                     = 1,        #usize
  max_stay_time                     = 7,       #usize
  default_daily_movement_distance   = 20,       #usize
  good_year_chance                  = 15,       #usize
  burn_in_period                    = 0,        #usize
  beta_w                            = 0.05,     #f64
  beta_b                            = 0.001,    #f64
  beta_c                            = 0.6,      #f64
  carcass_contact_prob              = 0.10,     #f64
  p_symptomatic                     = 0.5,      #f64
  n_starting_groups                 = 100,       #usize
  seed                              = 1234,     #u64
  max_hr_cells                      = 1800,     #usize
  min_hr_cells                      = 1000,     #usize
  hr_border_fuzzy                   = 0.1,      #f32
  ap_max_jitter                     = 8,        #isize
  ap_jitter_factor                  = 2,        #isize
  min_ap                            = 4         #i32
)

write_json(config, "config.json", auto_unbox = TRUE, pretty = TRUE)

# Serialize and send input to Rust
input_json <- toJSON(input_data, auto_unbox = TRUE)
cat(input_json, file = "stdin")

# Call Rust executable 
rust_output <- system2("path", stdout = TRUE)

# Deserialize and process output in R
output_data <- fromJSON(rust_output)

#test
print(output_data)



system2("D:/OneDrive/Projects/asf_bavaria/Prototype/asf_model_bav_prototype/target/debug/asf_model_bav_prototype.exe", stdout = TRUE)




```

